FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /source
COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app
COPY --from=build /app .

CMD ["dotnet", "Worker.dll"]